version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: oneai-postgres
    environment:
      POSTGRES_USER: oneai
      POSTGRES_PASSWORD: oneai123
      POSTGRES_DB: oneai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
