name: Deploy to AWS

# 언제 실행할지 (main 브랜치에 push할 때)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 코드 다운로드
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. AWS 인증 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    # 3. S3에 파일 업로드 (예시)
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://oneai-frontend-7469/ --delete
        echo "배포 완료!"
